version: "3.8"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    volumes: [ "db_data:/var/lib/mysql" ]
    healthcheck: { test: ["CMD","mysqladmin","ping","-h","localhost"], interval: 5s, timeout: 5s, retries: 20 }
  wordpress:
    image: wordpress:latest
    depends_on: [ db ]
    ports: [ "8080:80" ]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wordpress
    volumes: [ "wp_data:/var/www/html" ]
  wpcli:
    image: wordpress:cli
    depends_on: [ wordpress ]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
volumes: { db_data: {}, wp_data: {} } 